### PR TITLE
Add testing

### PR DESCRIPTION
**Pull request by RyanJarv**
Work in progress for #11, figured I'd open a PR so people know it's here for now. Let me know if anyone has any suggestions or comments on it.

### CODE REVIEW

**Comment by RyanJarv** [comment]
Believe I got most of the currently used functions here. May come have to come back to the rest later.

**Comment by NejcZdovc** [comment]
cc @mrose17 @diracdeltas @evq

**Comment by evq** [comment]
OMG tests :heart_eyes:

Hey @RyanJarv, thank you so much for taking the time to put together these tests for our ledger client!

I'm really sorry, but unfortunately we won't be merging this pull request. We've actually moved core development of our ledger client to https://github.com/brave-intl/bat-client to coincide with our migration from the BTC payments system to our new BAT based system. I haven't looked closely yet, but we may be able to re-use and adjust some of these tests there. We are also looking at re-writing the ledger client to be more easily usable across various platforms so it may be we just take inspiration from these tests as that work proceeds.

Thanks again for contributing!

P.S. I'll be pushing some updates that point at our new repos to make it more clear what is actively being developed. Sorry we haven't already done that!

**Comment by RyanJarv** [comment]
Ah ok, I suppose that makes now that I think about it.. Well hopefully those will be useful for reference at least.

**Pull request closed without merging**
