### PR TITLE
error in initial update of this.state.ruleset doesn't crash client

### PR DESCRIPTION
**Pull request by willy-b**
When `Client#sync` can't fetch `this.state.ruleset` using `Client#_updateRules` the error handler was calling `this._log` when `this` was not bound to the Client instance and crashing (client/brave). Just added `.bind(this)` to fix.

fixes https://github.com/brave/ledger-client/commit/d38a8bc67d8c1d82885aac2c2cf427b47c378389#commitcomment-19057449

### CODE REVIEW

**Comment by mrose17** [comment]
i'm pretty sure that the current version of this package doesn't have that bug.

i'd rather not s/self/this/g throughout the code. would that be ok?

**Comment by willy-b** [comment]
We can use `self` here to fix the bug. The problem is that it is currently using `this` right now when `this` is not bound. I can resubmit with `self` instead. 

You only see the bug if the _updateRules call to the Ledger server fails, so this is probably low priority. A reproduction for the bug which works with latest ledger-client/brave is below. 

Reproduction:
- edit your `/etc/hosts` to point `ledger.brave.com` to some blackhole IP
- clear your `brave-development/ledger-*.json` files
- open Brave
- navigate to Payments tab and click "Create Wallet"
- observe Brave crashes

**Comment by mrose17** [comment]
thanks! now i get it. could you just s/this/self/ inside the callback? (you can tell that i'm from the "dense code" school of coding.)

@ayumi - this looks good to me. when the new commit comes in, if you're happy with it, please merge,  bump the version number, push, etc., and then `npm publish` using the "brave.com" user on npm? thanks!

**Comment by mrose17** [comment]
incorporated into earlier merge.

@willy-b -- thanks! i totally missed this until you pointed it out (twice).

**Pull request closed without merging**
